enhancements:
 - head-branch: ['^feature', 'feature']

dependencies:
- any:
  - changed-files:
    - any-glob-to-any-file: 'Makefile'
  - changed-files:
    - any-glob-to-any-file: '*.mod'
  - changed-files:
    - any-glob-to-any-file: '*.sum'

kind/documentation:
- any:
  - changed-files:
    - any-glob-to-any-file: 'docs/*'
  - changed-files:
    - any-glob-to-any-file: '*.md'

area/ai-model:
- any:
  - changed-files:
    - any-glob-to-any-file: 'gallery/*'

examples:
- any:
  - changed-files:
    - any-glob-to-any-file: 'examples/*'

ci:
- any:
  - changed-files:
    - any-glob-to-any-file: '.github/*'
