name: Build and Release

on:
  push:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "gallery/**"
      - "**.tmpl"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "gallery/**"
      - "**.tmpl"
      - "**.md"

permissions:
  contents: write

concurrency:
  group: ci-releases-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platforms: ["amd64", "arm64"]
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-qemu-action@v3
      - name: Build
        run: |
          docker build . \
          --target release-binaries \
          --platform linux/${{ matrix.platforms }} \
          --output release \
          --cache-from type=gha,scope=$GITHUB_REF_NAME-${{ matrix.platforms }}-release \
          --cache-to type=gha,mode=max,scope=$GITHUB_REF_NAME-${{ matrix.platforms }}-release
      - uses: actions/upload-artifact@v4
        with:
          name: LocalAI-linux
          path: release/
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/*

  build-macOS-arm64:
    runs-on: macos-14
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: false
      - name: Dependencies
        run: |
          brew install protobuf grpc
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@8ba23be9613c672d40ae261d2a1335d639bdd59b
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.0
      - name: Build
        id: build
        run: |
          export C_INCLUDE_PATH=/usr/local/include
          export CPLUS_INCLUDE_PATH=/usr/local/include
          export PATH=$PATH:$GOPATH/bin
          GO_TAGS=p2p make dist
      - uses: actions/upload-artifact@v4
        with:
          name: LocalAI-MacOS-arm64
          path: release/
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/*
